# Generated by Django 4.2.5 on 2023-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvarient',
            name='color_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
