# Generated by Django 4.2.5 on 2023-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_varients',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
