# Generated by Django 4.2.5 on 2023-10-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryManagement', '0001_initial'),
        ('product', '0002_product_varients_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kill_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoryManagement.category'),
        ),
    ]
