# Generated by Django 4.2.5 on 2023-09-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvarient_ramvarient_remove_product_ription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_varient',
            field=models.ManyToManyField(blank=True, to='product.colorvarient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_varient',
            field=models.ManyToManyField(blank=True, to='product.ramvarient'),
        ),
    ]
