# Generated by Django 4.2.5 on 2023-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_colorvarient_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramvarient',
            name='ram_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
