# Generated by Django 4.2.5 on 2023-09-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modefied_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
