# Generated by Django 4.2.5 on 2023-10-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_rayzor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Cancelled by Admin', 'Cancelled by Admin'), ('Return', 'Return')], default='New', max_length=30),
        ),
    ]
