# Generated by Django 4.2.5 on 2023-10-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
