# Generated by Django 4.2.5 on 2023-10-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
    ]
