# Generated by Django 4.2.5 on 2023-11-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_wallet_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
