# Generated by Django 4.2.5 on 2023-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMainSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('subheading', models.CharField(max_length=30, null=True)),
                ('slide_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
