# Generated by Django 4.2.5 on 2023-11-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
