# Generated by Django 4.2.5 on 2023-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_homemainslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemainslide',
            name='slide_image',
            field=models.ImageField(upload_to='banners'),
        ),
    ]
