# Generated by Django 4.2.5 on 2023-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
