# Generated by Django 4.2.5 on 2023-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_kill_switch_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('product_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_offer_image', models.ImageField(upload_to='offers')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='product.product_varients')),
            ],
        ),
    ]
